name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /srv/react-admin-2/
            git config --global user.email "xaveeg@gmail.com"
            git config --global user.name "BDKX16"
            git remote set-url origin https://BDKX16:${{ secrets.TOKEN }}@github.com/BDKX16/react-admin-2.git
            docker compose down
            git pull origin main
            docker compose up -d --build
